package com.srcim2018.semanticmodelimpl;

import com.srcim2018.semanticmodelimpl.impl.*;


import java.util.Collection;

import org.protege.owl.codegeneration.CodeGenerationFactory;
import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.FactoryHelper;
import org.protege.owl.codegeneration.impl.ProtegeJavaMapping;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.protege.owl.codegeneration.inference.SimpleInference;

import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyStorageException;

/**
 * A class that serves as the entry point to the generated code providing access
 * to existing individuals in the ontology and the ability to create new individuals in the ontology.<p>
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: MyFactory<br>
 * @version generated on Wed Apr 03 18:34:49 WEST 2019 by root
 */
public class MyFactory implements CodeGenerationFactory {
    private OWLOntology ontology;
    private ProtegeJavaMapping javaMapping = new ProtegeJavaMapping();
    private FactoryHelper delegate;
    private CodeGenerationInference inference;

    public MyFactory(OWLOntology ontology) {
	    this(ontology, new SimpleInference(ontology));
    }
    
    public MyFactory(OWLOntology ontology, CodeGenerationInference inference) {
        this.ontology = ontology;
        this.inference = inference;
        javaMapping.initialize(ontology, inference);
        delegate = new FactoryHelper(ontology, inference);
    }

    public OWLOntology getOwlOntology() {
        return ontology;
    }
    
    public void saveOwlOntology() throws OWLOntologyStorageException {
        ontology.getOWLOntologyManager().saveOntology(ontology);
    }
    
    public void flushOwlReasoner() {
        delegate.flushOwlReasoner();
    }
    
    public boolean canAs(WrappedIndividual resource, Class<? extends WrappedIndividual> javaInterface) {
    	return javaMapping.canAs(resource, javaInterface);
    }
    
    public  <X extends WrappedIndividual> X as(WrappedIndividual resource, Class<? extends X> javaInterface) {
    	return javaMapping.as(resource, javaInterface);
    }
    
    public Class<?> getJavaInterfaceFromOwlClass(OWLClass cls) {
        return javaMapping.getJavaInterfaceFromOwlClass(cls);
    }
    
    public OWLClass getOwlClassFromJavaInterface(Class<?> javaInterface) {
	    return javaMapping.getOwlClassFromJavaInterface(javaInterface);
    }
    
    public CodeGenerationInference getInference() {
        return inference;
    }

    /* ***************************************************
     * Class http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Conveyor
     */

    {
        javaMapping.add("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Conveyor", Conveyor.class, DefaultConveyor.class);
    }

    /**
     * Creates an instance of type Conveyor.  Modifies the underlying ontology.
     */
    public Conveyor createConveyor(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_CONVEYOR, DefaultConveyor.class);
    }

    /**
     * Gets an instance of type Conveyor with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Conveyor getConveyor(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_CONVEYOR, DefaultConveyor.class);
    }

    /**
     * Gets all instances of Conveyor from the ontology.
     */
    public Collection<? extends Conveyor> getAllConveyorInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_CONVEYOR, DefaultConveyor.class);
    }


    /* ***************************************************
     * Class http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Product
     */

    {
        javaMapping.add("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Product", Product.class, DefaultProduct.class);
    }

    /**
     * Creates an instance of type Product.  Modifies the underlying ontology.
     */
    public Product createProduct(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_PRODUCT, DefaultProduct.class);
    }

    /**
     * Gets an instance of type Product with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Product getProduct(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_PRODUCT, DefaultProduct.class);
    }

    /**
     * Gets all instances of Product from the ontology.
     */
    public Collection<? extends Product> getAllProductInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_PRODUCT, DefaultProduct.class);
    }


    /* ***************************************************
     * Class http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Resouce
     */

    {
        javaMapping.add("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Resouce", Resouce.class, DefaultResouce.class);
    }

    /**
     * Creates an instance of type Resouce.  Modifies the underlying ontology.
     */
    public Resouce createResouce(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_RESOUCE, DefaultResouce.class);
    }

    /**
     * Gets an instance of type Resouce with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Resouce getResouce(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_RESOUCE, DefaultResouce.class);
    }

    /**
     * Gets all instances of Resouce from the ontology.
     */
    public Collection<? extends Resouce> getAllResouceInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_RESOUCE, DefaultResouce.class);
    }


    /* ***************************************************
     * Class http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Skill
     */

    {
        javaMapping.add("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Skill", Skill.class, DefaultSkill.class);
    }

    /**
     * Creates an instance of type Skill.  Modifies the underlying ontology.
     */
    public Skill createSkill(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_SKILL, DefaultSkill.class);
    }

    /**
     * Gets an instance of type Skill with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Skill getSkill(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_SKILL, DefaultSkill.class);
    }

    /**
     * Gets all instances of Skill from the ontology.
     */
    public Collection<? extends Skill> getAllSkillInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_SKILL, DefaultSkill.class);
    }


}
