package com.srcim2018.semanticmodelimpl;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Product <br>
 * @version generated on Wed Apr 03 18:34:49 WEST 2019 by root
 */

public interface Product extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/consumes
     */
     
    /**
     * Gets all property values for the consumes property.<p>
     * 
     * @returns a collection of values for the consumes property.
     */
    Collection<? extends Skill> getConsumes();

    /**
     * Checks if the class has a consumes property value.<p>
     * 
     * @return true if there is a consumes property value.
     */
    boolean hasConsumes();

    /**
     * Adds a consumes property value.<p>
     * 
     * @param newConsumes the consumes property value to be added
     */
    void addConsumes(Skill newConsumes);

    /**
     * Removes a consumes property value.<p>
     * 
     * @param oldConsumes the consumes property value to be removed.
     */
    void removeConsumes(Skill oldConsumes);


    /* ***************************************************
     * Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology#InitialPosition
     */
     
    /**
     * Gets all property values for the InitialPosition property.<p>
     * 
     * @returns a collection of values for the InitialPosition property.
     */
    Collection<? extends String> getInitialPosition();

    /**
     * Checks if the class has a InitialPosition property value.<p>
     * 
     * @return true if there is a InitialPosition property value.
     */
    boolean hasInitialPosition();

    /**
     * Adds a InitialPosition property value.<p>
     * 
     * @param newInitialPosition the InitialPosition property value to be added
     */
    void addInitialPosition(String newInitialPosition);

    /**
     * Removes a InitialPosition property value.<p>
     * 
     * @param oldInitialPosition the InitialPosition property value to be removed.
     */
    void removeInitialPosition(String oldInitialPosition);



    /* ***************************************************
     * Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Description
     */
     
    /**
     * Gets all property values for the Description property.<p>
     * 
     * @returns a collection of values for the Description property.
     */
    Collection<? extends String> getDescription();

    /**
     * Checks if the class has a Description property value.<p>
     * 
     * @return true if there is a Description property value.
     */
    boolean hasDescription();

    /**
     * Adds a Description property value.<p>
     * 
     * @param newDescription the Description property value to be added
     */
    void addDescription(String newDescription);

    /**
     * Removes a Description property value.<p>
     * 
     * @param oldDescription the Description property value to be removed.
     */
    void removeDescription(String oldDescription);



    /* ***************************************************
     * Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Destiny
     */
     
    /**
     * Gets all property values for the Destiny property.<p>
     * 
     * @returns a collection of values for the Destiny property.
     */
    Collection<? extends String> getDestiny();

    /**
     * Checks if the class has a Destiny property value.<p>
     * 
     * @return true if there is a Destiny property value.
     */
    boolean hasDestiny();

    /**
     * Adds a Destiny property value.<p>
     * 
     * @param newDestiny the Destiny property value to be added
     */
    void addDestiny(String newDestiny);

    /**
     * Removes a Destiny property value.<p>
     * 
     * @param oldDestiny the Destiny property value to be removed.
     */
    void removeDestiny(String oldDestiny);



    /* ***************************************************
     * Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/ID
     */
     
    /**
     * Gets all property values for the ID property.<p>
     * 
     * @returns a collection of values for the ID property.
     */
    Collection<? extends String> getID();

    /**
     * Checks if the class has a ID property value.<p>
     * 
     * @return true if there is a ID property value.
     */
    boolean hasID();

    /**
     * Adds a ID property value.<p>
     * 
     * @param newID the ID property value to be added
     */
    void addID(String newID);

    /**
     * Removes a ID property value.<p>
     * 
     * @param oldID the ID property value to be removed.
     */
    void removeID(String oldID);



    /* ***************************************************
     * Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/ResourceExecutor
     */
     
    /**
     * Gets all property values for the ResourceExecutor property.<p>
     * 
     * @returns a collection of values for the ResourceExecutor property.
     */
    Collection<? extends String> getResourceExecutor();

    /**
     * Checks if the class has a ResourceExecutor property value.<p>
     * 
     * @return true if there is a ResourceExecutor property value.
     */
    boolean hasResourceExecutor();

    /**
     * Adds a ResourceExecutor property value.<p>
     * 
     * @param newResourceExecutor the ResourceExecutor property value to be added
     */
    void addResourceExecutor(String newResourceExecutor);

    /**
     * Removes a ResourceExecutor property value.<p>
     * 
     * @param oldResourceExecutor the ResourceExecutor property value to be removed.
     */
    void removeResourceExecutor(String oldResourceExecutor);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
