package com.srcim2018.semanticmodelimpl;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Skill <br>
 * @version generated on Wed Apr 03 18:34:49 WEST 2019 by root
 */

public interface Skill extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Description
     */
     
    /**
     * Gets all property values for the Description property.<p>
     * 
     * @returns a collection of values for the Description property.
     */
    Collection<? extends String> getDescription();

    /**
     * Checks if the class has a Description property value.<p>
     * 
     * @return true if there is a Description property value.
     */
    boolean hasDescription();

    /**
     * Adds a Description property value.<p>
     * 
     * @param newDescription the Description property value to be added
     */
    void addDescription(String newDescription);

    /**
     * Removes a Description property value.<p>
     * 
     * @param oldDescription the Description property value to be removed.
     */
    void removeDescription(String oldDescription);



    /* ***************************************************
     * Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/ID
     */
     
    /**
     * Gets all property values for the ID property.<p>
     * 
     * @returns a collection of values for the ID property.
     */
    Collection<? extends String> getID();

    /**
     * Checks if the class has a ID property value.<p>
     * 
     * @return true if there is a ID property value.
     */
    boolean hasID();

    /**
     * Adds a ID property value.<p>
     * 
     * @param newID the ID property value to be added
     */
    void addID(String newID);

    /**
     * Removes a ID property value.<p>
     * 
     * @param oldID the ID property value to be removed.
     */
    void removeID(String oldID);



    /* ***************************************************
     * Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Priority
     */
     
    /**
     * Gets all property values for the Priority property.<p>
     * 
     * @returns a collection of values for the Priority property.
     */
    Collection<? extends Integer> getPriority();

    /**
     * Checks if the class has a Priority property value.<p>
     * 
     * @return true if there is a Priority property value.
     */
    boolean hasPriority();

    /**
     * Adds a Priority property value.<p>
     * 
     * @param newPriority the Priority property value to be added
     */
    void addPriority(Integer newPriority);

    /**
     * Removes a Priority property value.<p>
     * 
     * @param oldPriority the Priority property value to be removed.
     */
    void removePriority(Integer oldPriority);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
