package com.srcim2018.semanticmodelimpl;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Wed Apr 03 18:34:49 WEST 2019 by root
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Conveyor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONVEYOR.<p>
     * 
     */
    public static final OWLClass CLASS_CONVEYOR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Conveyor"));

    /* ***************************************************
     * Class http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Product
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRODUCT.<p>
     * 
     */
    public static final OWLClass CLASS_PRODUCT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Product"));

    /* ***************************************************
     * Class http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Resouce
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESOUCE.<p>
     * 
     */
    public static final OWLClass CLASS_RESOUCE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Resouce"));

    /* ***************************************************
     * Class http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Skill
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SKILL.<p>
     * 
     */
    public static final OWLClass CLASS_SKILL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Skill"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/consumes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONSUMES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONSUMES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/consumes"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/executes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXECUTES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXECUTES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/executes"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/plugged
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PLUGGED.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PLUGGED = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/plugged"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology#DeviceID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEVICEID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEVICEID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology#DeviceID"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology#InitialPosition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INITIALPOSITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INITIALPOSITION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology#InitialPosition"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Description
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DESCRIPTION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Description"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Destiny
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DESTINY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DESTINY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Destiny"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/ID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/ID"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/NextConveyor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NEXTCONVEYOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NEXTCONVEYOR = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/NextConveyor"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Priority
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PRIORITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PRIORITY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/Priority"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/ResourceExecutor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property RESOURCEEXECUTOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_RESOURCEEXECUTOR = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/srcim2018/ontologies/srcimOntology/ResourceExecutor"));


}
